/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as VerifyEmailRouteImport } from './routes/Verify-email'
import { Route as RegisterRouteImport } from './routes/Register'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollsIndexRouteImport } from './routes/polls/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email/$token'
import { Route as PollCreateRouteImport } from './routes/poll/create'
import { Route as PollPollIdIndexRouteImport } from './routes/poll/$pollId/index'
import { Route as QuestionQuestionIdOptionsAddRouteImport } from './routes/question/$questionId/options/add'
import { Route as PollPollIdQuestionsAddRouteImport } from './routes/poll/$pollId/questions/add'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/Verify-email',
  path: '/Verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PollCreateRoute = PollCreateRouteImport.update({
  id: '/poll/create',
  path: '/poll/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdIndexRoute = PollPollIdIndexRouteImport.update({
  id: '/poll/$pollId/',
  path: '/poll/$pollId/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionQuestionIdOptionsAddRoute =
  QuestionQuestionIdOptionsAddRouteImport.update({
    id: '/question/$questionId/options/add',
    path: '/question/$questionId/options/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const PollPollIdQuestionsAddRoute = PollPollIdQuestionsAddRouteImport.update({
  id: '/poll/$pollId/questions/add',
  path: '/poll/$pollId/questions/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/polls/': typeof PollsIndexRoute
  '/poll/$pollId/': typeof PollPollIdIndexRoute
  '/poll/$pollId/questions/add': typeof PollPollIdQuestionsAddRoute
  '/question/$questionId/options/add': typeof QuestionQuestionIdOptionsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/polls': typeof PollsIndexRoute
  '/poll/$pollId': typeof PollPollIdIndexRoute
  '/poll/$pollId/questions/add': typeof PollPollIdQuestionsAddRoute
  '/question/$questionId/options/add': typeof QuestionQuestionIdOptionsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof DashboardRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/polls/': typeof PollsIndexRoute
  '/poll/$pollId/': typeof PollPollIdIndexRoute
  '/poll/$pollId/questions/add': typeof PollPollIdQuestionsAddRoute
  '/question/$questionId/options/add': typeof QuestionQuestionIdOptionsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/dashboard'
    | '/poll/create'
    | '/verify-email/$token'
    | '/polls/'
    | '/poll/$pollId/'
    | '/poll/$pollId/questions/add'
    | '/question/$questionId/options/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/dashboard'
    | '/poll/create'
    | '/verify-email/$token'
    | '/polls'
    | '/poll/$pollId'
    | '/poll/$pollId/questions/add'
    | '/question/$questionId/options/add'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/dashboard'
    | '/poll/create'
    | '/verify-email/$token'
    | '/polls/'
    | '/poll/$pollId/'
    | '/poll/$pollId/questions/add'
    | '/question/$questionId/options/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DashboardRoute: typeof DashboardRoute
  PollCreateRoute: typeof PollCreateRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  PollsIndexRoute: typeof PollsIndexRoute
  PollPollIdIndexRoute: typeof PollPollIdIndexRoute
  PollPollIdQuestionsAddRoute: typeof PollPollIdQuestionsAddRoute
  QuestionQuestionIdOptionsAddRoute: typeof QuestionQuestionIdOptionsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Verify-email': {
      id: '/Verify-email'
      path: '/Verify-email'
      fullPath: '/Verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/create': {
      id: '/poll/create'
      path: '/poll/create'
      fullPath: '/poll/create'
      preLoaderRoute: typeof PollCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId/': {
      id: '/poll/$pollId/'
      path: '/poll/$pollId'
      fullPath: '/poll/$pollId/'
      preLoaderRoute: typeof PollPollIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question/$questionId/options/add': {
      id: '/question/$questionId/options/add'
      path: '/question/$questionId/options/add'
      fullPath: '/question/$questionId/options/add'
      preLoaderRoute: typeof QuestionQuestionIdOptionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/$pollId/questions/add': {
      id: '/poll/$pollId/questions/add'
      path: '/poll/$pollId/questions/add'
      fullPath: '/poll/$pollId/questions/add'
      preLoaderRoute: typeof PollPollIdQuestionsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DashboardRoute: DashboardRoute,
  PollCreateRoute: PollCreateRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  PollsIndexRoute: PollsIndexRoute,
  PollPollIdIndexRoute: PollPollIdIndexRoute,
  PollPollIdQuestionsAddRoute: PollPollIdQuestionsAddRoute,
  QuestionQuestionIdOptionsAddRoute: QuestionQuestionIdOptionsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
