/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/Verify-email'
import { Route as RegisterRouteImport } from './routes/Register'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollIndexRouteImport } from './routes/poll/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email/$token'
import { Route as PollCreateRouteImport } from './routes/poll/create'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/Verify-email',
  path: '/Verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollIndexRoute = PollIndexRouteImport.update({
  id: '/poll/',
  path: '/poll/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PollCreateRoute = PollCreateRouteImport.update({
  id: '/poll/create',
  path: '/poll/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/poll/': typeof PollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/poll': typeof PollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Register': typeof RegisterRoute
  '/Verify-email': typeof VerifyEmailRoute
  '/poll/create': typeof PollCreateRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/poll/': typeof PollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/poll/create'
    | '/verify-email/$token'
    | '/poll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/poll/create'
    | '/verify-email/$token'
    | '/poll'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Register'
    | '/Verify-email'
    | '/poll/create'
    | '/verify-email/$token'
    | '/poll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PollCreateRoute: typeof PollCreateRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  PollIndexRoute: typeof PollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Verify-email': {
      id: '/Verify-email'
      path: '/Verify-email'
      fullPath: '/Verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/': {
      id: '/poll/'
      path: '/poll'
      fullPath: '/poll/'
      preLoaderRoute: typeof PollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poll/create': {
      id: '/poll/create'
      path: '/poll/create'
      fullPath: '/poll/create'
      preLoaderRoute: typeof PollCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PollCreateRoute: PollCreateRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  PollIndexRoute: PollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
